# Generated by Django 5.2 on 2025-04-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedophile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Baiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baiter')),
                ('Pedophile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedophile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('converation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conversation')),
            ],
        ),
        migrations.AddField(
            model_name='pedophile',
            name='socialNetwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.socialnetwork'),
        ),
        migrations.AddField(
            model_name='baiter',
            name='socialNetwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.socialnetwork'),
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('socialNetwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.socialnetwork')),
            ],
        ),
    ]
