# Generated by Django 5.2 on 2025-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='Baiter',
            new_name='baiter',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='Pedophile',
            new_name='pedophile',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('assistant', 'Baiter'), ('user', 'Pedophile'), ('systeme', 'Systeme')], default='baiter', max_length=10),
            preserve_default=False,
        ),
    ]
