# Generated by Django 5.2 on 2025-04-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_baiter_conversation_baiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiter',
            name='gender',
            field=models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl')], max_length=10),
        ),
    ]
